export const VIEW_DOCTORS_REQUEST = 'VIEW_DOCTORS_REQUEST';
export const VIEW_DOCTORS_SUCCESS = 'VIEW_DOCTORS_SUCCESS';
export const VIEW_DOCTORS_FAILURE = 'VIEW_DOCTORS_FAILURE';
export const VERIFY_DOCTOR_REQUEST = 'VERIFY_DOCTOR_REQUEST';
export const VERIFY_DOCTOR_SUCCESS = 'VERIFY_DOCTOR_SUCCESS';
export const VERIFY_DOCTOR_FAILURE = 'VERIFY_DOCTOR_FAILURE';
export const UNVERIFY_DOCTOR_REQUEST = 'UNVERIFY_DOCTOR_REQUEST';
export const UNVERIFY_DOCTOR_SUCCESS = 'UNVERIFY_DOCTOR_SUCCESS';
export const UNVERIFY_DOCTOR_FAILURE = 'UNVERIFY_DOCTOR_FAILURE';

export const VIEW_PATIENTS_REQUEST = 'VIEW_PATIENTS_REQUEST';
export const VIEW_PATIENTS_SUCCESS = 'VIEW_PATIENTS_SUCCESS';
export const VIEW_PATIENTS_FAILURE = 'VIEW_PATIENTS_FAILURE';
export const VERIFY_PATIENT_REQUEST = 'VERIFY_PATIENT_REQUEST';
export const VERIFY_PATIENT_SUCCESS = 'VERIFY_PATIENT_SUCCESS';
export const VERIFY_PATIENT_FAILURE = 'VERIFY_PATIENT_FAILURE';
export const UNVERIFY_PATIENT_REQUEST = 'UNVERIFY_PATIENT_REQUEST';
export const   unverifyDoctorSuccess= 'UNVERIFY_PATIENT_SUCCESS';
export const unverifyDoctorFailure  = 'UNVERIFY_PATIENT_FAILURE';

export const FETCH_USER_DATA_REQUEST = 'user/fetchUserDataRequest';
export const FETCH_USER_DATA_FAILURE = 'user/fetchUserDataFailure';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'UPDATE_USER_DATA_ERROR';
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR';

export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';